site_name: AATools Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - AATools Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - Explanation: 
    - Design overview: explanation/index.md
    - Model evaluation rationale: explanation/model-evaluation.md