site_name: AATools Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - AATools Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - Explanation: 
    - Design overview: explanation/index.md
    - Model evaluation rationale: explanation/model-evaluation.md